"""add_article_quality_and_rag_context

Revision ID: 2765686cfdec
Revises: de24db737c95
Create Date: 2026-07-01 23:09:05.313865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2765686cfdec'
down_revision: Union[str, None] = 'de24db737c95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('quality_score', sa.Float(), server_default='1.00', nullable=False))
    op.add_column('stories', sa.Column('rag_context', sa.JSON(), nullable=True))
    op.add_column('stories', sa.Column('representative_article_id', sa.Uuid(), nullable=True))
    op.add_column('stories', sa.Column('publisher_diversity', sa.Integer(), server_default='1', nullable=False))
    op.create_foreign_key('fk_stories_representative_article', 'stories', 'articles', ['representative_article_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_stories_representative_article', 'stories', type_='foreignkey')
    op.drop_column('stories', 'publisher_diversity')
    op.drop_column('stories', 'representative_article_id')
    op.drop_column('stories', 'rag_context')
    op.drop_column('articles', 'quality_score')
    # ### end Alembic commands ###
