"""add_event_type_to_timelines

Revision ID: 55cc5fa69f31
Revises: 7218467763db
Create Date: 2026-07-04 04:14:14.439828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55cc5fa69f31'
down_revision: Union[str, None] = '7218467763db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story_timelines', sa.Column('event_type', sa.String(length=50), server_default='update', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story_timelines', 'event_type')
    # ### end Alembic commands ###
