"""add_story_verification_fields

Revision ID: 7218467763db
Revises: 2765686cfdec
Create Date: 2026-07-04 03:51:27.641824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7218467763db'
down_revision: Union[str, None] = '2765686cfdec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('evidence', sa.JSON(), nullable=True))
    op.add_column('stories', sa.Column('has_conflicts', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('story_relations', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story_relations', 'created_at')
    op.drop_column('stories', 'has_conflicts')
    op.drop_column('stories', 'evidence')
    # ### end Alembic commands ###
