"""Add story and article metadata fields

Revision ID: 7f7bbd37d8cb
Revises: 5c3a94f02151
Create Date: 2026-06-27 18:45:05.556253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f7bbd37d8cb'
down_revision: Union[str, None] = '5c3a94f02151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_relations',
    sa.Column('parent_story_id', sa.Uuid(), nullable=False),
    sa.Column('child_story_id', sa.Uuid(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['child_story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_story_id', 'child_story_id')
    )
    op.add_column('articles', sa.Column('subtitle', sa.String(length=512), nullable=True))
    op.add_column('articles', sa.Column('country', sa.String(length=50), nullable=True))
    op.add_column('articles', sa.Column('reading_time', sa.Integer(), nullable=True))
    op.add_column('articles', sa.Column('word_count', sa.Integer(), nullable=True))
    op.add_column('articles', sa.Column('character_count', sa.Integer(), nullable=True))
    op.add_column('articles', sa.Column('qdrant_point_id', sa.String(length=36), nullable=True))
    op.add_column('articles', sa.Column('keywords', sa.JSON(), nullable=True))
    op.add_column('articles', sa.Column('named_entities', sa.JSON(), nullable=True))
    op.add_column('articles', sa.Column('topics', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_articles_qdrant_point_id'), 'articles', ['qdrant_point_id'], unique=False)
    op.add_column('stories', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('stories', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('stories', sa.Column('article_count', sa.Integer(), nullable=False))
    op.alter_column('stories', 'centroid_vector_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               nullable=True)
    op.alter_column('stories', 'summary_quick',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('stories', 'summary_beginner',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('stories', 'summary_professional',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stories', 'summary_professional',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('stories', 'summary_beginner',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('stories', 'summary_quick',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('stories', 'centroid_vector_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               nullable=False)
    op.drop_column('stories', 'article_count')
    op.drop_column('stories', 'status')
    op.drop_column('stories', 'summary')
    op.drop_index(op.f('ix_articles_qdrant_point_id'), table_name='articles')
    op.drop_column('articles', 'topics')
    op.drop_column('articles', 'named_entities')
    op.drop_column('articles', 'keywords')
    op.drop_column('articles', 'qdrant_point_id')
    op.drop_column('articles', 'character_count')
    op.drop_column('articles', 'word_count')
    op.drop_column('articles', 'reading_time')
    op.drop_column('articles', 'country')
    op.drop_column('articles', 'subtitle')
    op.drop_table('story_relations')
    # ### end Alembic commands ###
