"""add_milestone3_refinements

Revision ID: d75f7494c7cb
Revises: 55cc5fa69f31
Create Date: 2026-07-04 04:24:08.694283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd75f7494c7cb'
down_revision: Union[str, None] = '55cc5fa69f31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publishers', sa.Column('source_type', sa.String(length=50), server_default='LOCAL_NEWS', nullable=False))
    op.add_column('stories', sa.Column('verification_metadata', sa.JSON(), nullable=True))
    op.add_column('story_timelines', sa.Column('confidence_score', sa.Float(), server_default='1.0', nullable=False))
    op.add_column('story_timelines', sa.Column('supporting_articles', sa.Integer(), server_default='1', nullable=False))
    op.add_column('story_timelines', sa.Column('supporting_publishers', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story_timelines', 'supporting_publishers')
    op.drop_column('story_timelines', 'supporting_articles')
    op.drop_column('story_timelines', 'confidence_score')
    op.drop_column('stories', 'verification_metadata')
    op.drop_column('publishers', 'source_type')
    # ### end Alembic commands ###
