"""Add publisher feed health columns

Revision ID: f862c00452f7
Revises: 7f7bbd37d8cb
Create Date: 2026-06-27 19:11:57.873853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f862c00452f7'
down_revision: Union[str, None] = '7f7bbd37d8cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publishers', sa.Column('successful_fetches', sa.Integer(), nullable=True))
    op.add_column('publishers', sa.Column('failed_fetches', sa.Integer(), nullable=True))
    op.add_column('publishers', sa.Column('avg_latency_ms', sa.Float(), nullable=True))
    op.add_column('publishers', sa.Column('articles_per_fetch', sa.Float(), nullable=True))
    op.add_column('publishers', sa.Column('duplicate_percentage', sa.Float(), nullable=True))
    op.add_column('publishers', sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publishers', 'last_fetched_at')
    op.drop_column('publishers', 'duplicate_percentage')
    op.drop_column('publishers', 'articles_per_fetch')
    op.drop_column('publishers', 'avg_latency_ms')
    op.drop_column('publishers', 'failed_fetches')
    op.drop_column('publishers', 'successful_fetches')
    # ### end Alembic commands ###
