"""
UserRecommendationLog model — Milestone 4: Recommendation Engine.

Tracks every story served to every user for:
  - Click-through rate (CTR) measurement
  - Deduplication (don't re-serve within 24h)
  - Recommendation analytics and A/B testing

recommendation_metadata stores structured JSON — not free text.
Natural language explanations are generated by frontend/conversational AI
(Milestone 5/6) from this structured data at render time.
"""
import uuid
from datetime import datetime
from sqlalchemy import String, Numeric, DateTime, ForeignKey, Boolean, JSON, func
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.database.models.base import Base


class UserRecommendationLog(Base):
    """Tracks recommended stories served to users for feedback loops and metrics."""

    __tablename__ = "user_recommendation_logs"

    id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True,
        default=uuid.uuid4
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    story_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("stories.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )

    # Composite recommendation score after all ranking factors applied
    score: Mapped[float] = mapped_column(
        Numeric(5, 4),
        nullable=False
    )

    strategy: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        default="cold_start"
    )

    # Ranking algorithm version used (e.g., "v1") for A/B testing
    ranking_version: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default="v1",
        server_default="v1"
    )

    # Whether this recommendation used the personalized Qdrant ANN path
    is_personalized: Mapped[bool] = mapped_column(
        Boolean,
        default=False
    )

    # Structured explanation metadata — consumed by frontend / conversational AI.
    # Schema: {
    #   "strategy": "personalized",
    #   "semantic_similarity": 0.91,
    #   "composite_score": 0.84,
    #   "freshness_decay": 0.92,
    #   "matched_categories": ["AI", "Technology"],
    #   "boosts": ["credibility", "freshness"],
    #   "diversity_bucket": "HIGH"
    # }
    recommendation_metadata: Mapped[dict] = mapped_column(
        JSON,
        nullable=False,
        default=dict
    )

    # Set to True when the user clicks on this story (CTR tracking)
    clicked: Mapped[bool] = mapped_column(
        Boolean,
        default=False
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        index=True
    )

    # Relationships
    user = relationship("User", back_populates="recommendation_logs")

