"""
Story model for Heimdall Consumer Edition.

Changes from enterprise edition:
  - Removed: centroid_vector_id (Qdrant removed)
  - Removed: rag_context, formation_evidence (no RAG/ML)
  - Removed: summary_quick, summary_beginner, summary_professional (replaced by structured AI summary)
  - Removed: chat_sessions relationship (RAG chat removed)
  - Added: ai_summary (structured Gemini summary stored as text)
  - Added: ai_summary_at (when summary was generated)
  - Added: region_tags (list of regions: ["India", "Telangana", "Hyderabad"])
  - Added: view_count (for trending score calculation)
  - Added: search_vector (PostgreSQL full-text search index, managed by trigger)

Kept unchanged:
  - title, summary, status, confidence_score, article_count
  - importance_score, trending_score, evidence, verification_metadata
  - has_conflicts, publisher_diversity
  - verification_score, credibility_score, first_reported_at, last_updated_at
  - StoryRelation, StoryRelationType
  - Timestamps
"""
import uuid
from datetime import datetime
from enum import Enum
from typing import Optional
from sqlalchemy import Text, Numeric, DateTime, func, String, Integer, Float, JSON, ForeignKey
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.database.models.base import Base


class StoryRelationType(str, Enum):
    RELATED = "RELATED"
    FOLLOW_UP = "FOLLOW_UP"
    CAUSES = "CAUSES"
    MERGED_FROM = "MERGED_FROM"
    SPLIT_FROM = "SPLIT_FROM"
    CONTRADICTS = "CONTRADICTS"


class StoryRelation(Base):
    """Junction table for self-referencing story relationships."""

    __tablename__ = "story_relations"

    parent_story_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("stories.id", ondelete="CASCADE"),
        primary_key=True
    )
    child_story_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("stories.id", ondelete="CASCADE"),
        primary_key=True
    )
    relation_type: Mapped[str] = mapped_column(
        String(50),
        default=StoryRelationType.RELATED.value
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now()
    )


class Story(Base):
    """
    A Story is a cluster of related articles covering the same real-world event.

    Lifecycle: ACTIVE → MERGED → ARCHIVED
    """

    __tablename__ = "stories"

    id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True,
        default=uuid.uuid4
    )

    # Representative headline — title of the first/best article in this story
    title: Mapped[Optional[str]] = mapped_column(
        String(512),
        nullable=True
    )

    # Short generic summary (deterministic — from first article)
    summary: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True
    )

    # ── Gemini AI Summary ─────────────────────────────────────────────────────
    # Structured 6-section summary generated by services/summarizer.py at ingestion.
    # Format: markdown with sections: Main Event / Background / Timeline /
    #         Key People & Organizations / Impact / Why It Matters
    ai_summary: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True
    )
    ai_summary_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True
    )

    # ── Region ────────────────────────────────────────────────────────────────
    # List of detected geographic regions for this story (used in recommendation scoring).
    # Example: ["India", "Telangana", "Hyderabad"]
    region_tags: Mapped[Optional[list]] = mapped_column(
        JSON,
        nullable=True
    )

    # ── Trending ──────────────────────────────────────────────────────────────
    # Raw page/story views — used to compute trending_score (growth rate)
    view_count: Mapped[int] = mapped_column(
        Integer,
        default=0,
        server_default="0",
        nullable=False
    )

    # Story lifecycle state
    status: Mapped[str] = mapped_column(
        String(50),
        default="ACTIVE"
    )

    # Category predicted for the story (inherited from member articles)
    predicted_category: Mapped[Optional[str]] = mapped_column(
        String(100),
        nullable=True
    )

    # Clustering confidence
    confidence_score: Mapped[float] = mapped_column(
        Numeric(3, 2),
        default=1.00
    )
    article_count: Mapped[int] = mapped_column(
        Integer,
        default=1
    )

    # ── Scoring Signals ───────────────────────────────────────────────────────
    # Composite importance signal for ranking (0.0–1.0)
    importance_score: Mapped[float] = mapped_column(
        Float,
        default=0.0,
        nullable=False
    )
    # Recency + growth trending signal for home feed (0.0–1.0)
    trending_score: Mapped[float] = mapped_column(
        Float,
        default=0.0,
        nullable=False
    )

    # ── Verification ──────────────────────────────────────────────────────────
    evidence: Mapped[Optional[list]] = mapped_column(JSON, nullable=True)
    verification_metadata: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)
    has_conflicts: Mapped[bool] = mapped_column(default=False, server_default="false")

    # Centroid-nearest representative article (for cover image, headline)
    representative_article_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        ForeignKey(
            "articles.id",
            ondelete="SET NULL",
            use_alter=True,
            name="fk_stories_representative_article"
        ),
        nullable=True
    )

    # Unique publishers contributing to this story (used by verification label)
    publisher_diversity: Mapped[int] = mapped_column(
        Integer,
        default=1,
        nullable=False,
        server_default="1"
    )

    # Aggregate fact-check score (0.0–1.0)
    verification_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    credibility_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    first_reported_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    last_updated_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # ── Timestamps ────────────────────────────────────────────────────────────
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        index=True
    )

    # ── Relationships ─────────────────────────────────────────────────────────
    articles = relationship(
        "Article",
        back_populates="story",
        foreign_keys="[Article.story_id]"
    )
    representative_article = relationship(
        "Article",
        foreign_keys="[Story.representative_article_id]"
    )
    timelines = relationship(
        "StoryTimeline",
        back_populates="story",
        cascade="all, delete-orphan"
    )
    bookmarks = relationship(
        "Bookmark",
        back_populates="story",
        cascade="all, delete-orphan"
    )
    reading_history = relationship(
        "ReadingHistory",
        back_populates="story",
        cascade="all, delete-orphan"
    )
    related_stories = relationship(
        "Story",
        secondary="story_relations",
        primaryjoin="Story.id==StoryRelation.parent_story_id",
        secondaryjoin="Story.id==StoryRelation.child_story_id",
        backref="parent_stories"
    )
